# Generated by Django 2.1.5 on 2019-12-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inputmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputa', models.IntegerField(default='')),
                ('inputb', models.IntegerField(default='')),
            ],
        ),
    ]
